# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Greg Trafton
email: greg [.] trafton [at] nrl [.] navy [.] mil
#Write a description of Greg Trafton's research here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
description: >- # this means to ignore newlines until "baseurl:"
 I am a cognitive scientist at the Naval Research Laboratory in the Artificial Intelligence Center.
 
##baseurl: "" # the subpath of your site, e.g. /blog
##url: "" # the base hostname & protocol for your site, e.g. http://example.com
##repository: my-awesome-site
##port: 4444
### baseurl: "" # the subpath of your site, e.g. /blog
### url: "" # the base hostname & protocol for your site, e.g. http://example.com
### repository: my-awesome-site
### port: 4444
### trying to migrate it to bluehost...
baseurl: "" # the subpath of your site, e.g. /blog
### baseurl: "/public_html" # the subpath of your site, e.g. /blog
url: "http://gregtrafton.com" # the base hostname & protocol for your site, e.g. http://example.com
##repository: my-awesome-site ## not sure what this is
##port: 4444  ## Not needed when I am doing hosting (?)

# Build settings
markdown: kramdown
theme: minima #jekyll-theme-primer #plain-tufte-theme # default is 'minima'
plugins:
  - jekyll-feed

defaults:
  -
    scope: # stores path
      path: "" # tells us which files we want the defaults to be applied to (empty string = all files)
    values: # default values 
        author: "Greg Trafton"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
